apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "release.name" . }}
  labels:
    app: {{ include "release.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "release.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "release.name" . }}
    spec:
      containers:
      - name: discordant
        image: {{ .Values.repository }}:{{ .Values.revision }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "500Mi"
          requests:
            memory: "250Mi"
        env:
        {{- include "container.secrets.env" (list "discordant" .Values.secrets) | nindent 8 }}
        envFrom:
        - configMapRef:
            name: {{ include "release.name" . }}
        volumeMounts:
        {{- include "container.secrets.mounts" (list "discordant" .Values.secretFiles) | nindent 8 }}
      volumes:
      {{- include "container.secrets.volumes" (list "discordant" .Values.secretFiles) | nindent 6 }}
