repository: aufish/discordant
revision: v0.4.12

dal:
  config:
    driver: googlestorage
    googlestorage:
      bucket: discordant
      key: /tmp/creds/discordant-storage-rwd.json
  gif:
    driver: tenor

alwinn:
  period:
    min: 1m
    max: 5m
  inspiration_die: 8

turg:
  period:
    min: 1m
    max: 5m

secrets:
  discordant:
  - from: discordant
    prefix: dsc_alwinn
    values:
      token: alwinn-bot-token
  - from: discordant
    prefix: dsc_turg
    values:
      token: turg-bot-token
  - from: discordant
    prefix: dsc_dal_tenor
    values:
      token: tenor-token
  - from: discordant
    prefix: dsc_dal_giphy
    values:
      token: giphy-token

secretFiles:
  discordant:
  - from: discordant-storage-rwd
    path: /tmp/creds