repository: aufish/discordant
revision: v0.4.12

dal:
  config:
    driver: staticstorage
    googlestorage:
      bucket: none
      key: none
    staticstorage:
      dir: /opt/discordant/cfg

  gif:
    driver: tenor

alwinn:
  period:
    min: 1m
    max: 5m
  inspiration_die: 8

turg:
  period:
    min: 1m
    max: 5m

secrets:
  discordant:
  - from: discordant-local
    prefix: dsc_alwinn
    values:
      token: alwinn-bot-token
  - from: discordant-local
    prefix: dsc_turg
    values:
      token: turg-bot-token
  - from: discordant-local
    prefix: dsc_dal_tenor
    values:
      token: tenor-token
  - from: discordant-local
    prefix: dsc_dal_giphy
    values:
      token: giphy-token
